#Store aws credentials securely in kubernetes to access aws secret manager
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: default
type: Opaque
data:
  access-key-id: <base64-encoded-access-key-id>
  secret-access-key: <base64-encoded-secret-access-key>
