# Pull the RDS secrets for production dynamically form aws secret manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: production-rds-secret
  namespace: production
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: production-rds-secret
  data:
    - secretKey: username
      remoteRef:
        key: production-rds-secret
        property: username
    - secretKey: password
      remoteRef:
        key: production-rds-secret
        property: password
    - secretKey: host
      remoteRef:
        key: production-rds-secret
        property: host
