#  Pull the RDS secrets for staging dynamically from aws secret manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: staging-rds-secret
  namespace: staging
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: staging-rds-secret
  data:
    - secretKey: username
      remoteRef:
        key: staging-rds-secret
        property: username
    - secretKey: password
      remoteRef:
        key: staging-rds-secret
        property: password
    - secretKey: host
      remoteRef:
        key: staging-rds-secret
        property: host
